conference:    
    year: 2013
    location: 'Asheville, NC, USA'
    begin: 'August 4'
    end: 'August 8'

hosts:
    host1:
        name: 'Chris Janetopoulos'
        email: 'c.janetopoulos@vanderbilt.edu'
        affiliation: 'Departments of Biological Sciences and Cell & Developmental Biology, Vanderbilt University, Nashville TN'
    host2:
        name: 'Paul Steimle'
        email: 'p_steiml@uncg.edu'
        affiliation: 'Department of Biology, University of North Carolina at Greensboro, Greensboro NC'

# Available - Agenda, Registration, Abstracts, Travel, Sponsors
# Default - Home, Login
menubar: ["Registration", "Travel"]

agenda-file: 

registration:
    begin: '15th May 2013 00:00:00 AM'
    end: '26th Jul 2013 11:59:00 PM'

abstracts:
    begin: '15th May 2013 00:00:01 AM'
    end: '30th Jul 2013 11:59:00 PM'
